name: Publish
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout branch
        run: |
          git checkout -b master
          git branch -a

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: buildPlugin

      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.release_tag }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: Release.md
          prerelease: false
          files: |
            ./build/mirai/*.jar
