name: Publish

on:
  push:
    tags:
      - '*.*.*'
      - '*.*.*-dev'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout branch master
        if: "!contains(steps.tag.outputs.release_tag, 'dev')"
        run: git checkout -b master

      - name: Checkout branch dev
        if: "contains(steps.tag.outputs.release_tag, 'dev')"
        run: git checkout -b dev

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: current
          arguments: buildPlugin

      - name: Release Master
        if: "!contains(steps.tag.outputs.release_tag, 'dev')"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.release_tag }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: Release.md
          prerelease: false
          files: |
            ./build/mirai/*.jar

      - name: Release Dev
        if: "contains(steps.tag.outputs.release_tag, 'dev')"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.tag.outputs.release_tag }}
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: Release.md
          prerelease: true
          files: |
            ./build/mirai/*.jar
